package handlers

import (
	"bytes"
	"context"
	"encoding/binary"
	"encoding/json"
	"fmt"
	"net/http"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"sync"
	"time"

	"github.com/go-chi/chi/v5"
	"github.com/o3c/workspace/core"
)

// call_qa.go — on-demand call QA: transcribe a call's recording locally
// (whisper.cpp, no cloud STT — the same self-hosted-only rule assistant.go
// follows for customer PII) and score it against a rubric using the same
// local Ollama model the in-house assistant runs on. See migration 327 for
// why the model and rubric look the way they do: small.en fabricated errors
// on essentially every call by mishearing the company name and Nigerian
// place names, and large-v3-turbo plus a rubric that states ground-truth
// facts (company name, regulator, common place names, "snap" = photograph)
// was needed to get the false-positive rate down to something defensible.
//
// A row in call_qa_flags is a reason to look, never a verdict — a supervisor
// still has to read the transcript (and listen, if the reason isn't
// self-evident) before marking it reviewed/dismissed/actioned.
//
// One run at a time: whisper.cpp is single-threaded CPU-bound and this box
// has no dedicated inference hardware, so concurrent runs would just slow
// each other down rather than run in parallel. callQAMu serializes them.

var callQAMu sync.Mutex

func callQAToolsDir() string   { return filepath.Join(UploadRoot(), "qa-tools") }
func callQAWhisperBin() string { return filepath.Join(callQAToolsDir(), "whisper-cli.exe") }
func callQAModelPath() string {
	return filepath.Join(callQAToolsDir(), "models", "ggml-large-v3-turbo-q5_0.bin")
}

const callQAModelName = "ggml-large-v3-turbo-q5_0"

// Vocabulary hint fed to whisper as an initial prompt. Without this, the ASR
// substitutes the closest real English word it knows for anything it's never
// heard — "O3 Capital" became four different fake company names across a
// 10-call pilot before this was added, and "Sabo" (a real Lagos/Yaba area)
// became "Sabah" (a Malaysian state).
const callQAVocabPrompt = "O3 Capital, CBN, Central Bank of Nigeria, Lagos, Abuja, Sabo, Yaba, Ikeja, Apapa, Lekki, Surulere, Ajah, BVN, NIN, Zoho, WhatsApp."

const callQARubric = `You are reviewing a transcript of a phone call made by an agent at a Nigerian
consumer lending company (O3 Capital) to a customer, for call-quality QA purposes. The
transcript is auto-generated by speech-to-text and WILL contain mishearing errors,
especially on the company name and local place names — do not treat those as agent
mistakes. Ground truth, so you can tell a real error from a mishearing:
  - The company is "O3 Capital" (may be misheard as "U-3 capital", "All three capital",
    "Woodbury Capital", "Autry Capital", "Autarik", etc. — these are ASR errors, not the
    agent naming the wrong company).
  - The regulator is the CBN (Central Bank of Nigeria) — "CDN" or similar is an ASR
    mishearing of CBN, not the agent naming the wrong regulator.
  - Nigerian place names the ASR may mangle into unrelated English/foreign words it
    knows instead (e.g. "Sabo" -> "Sabah"): Sabo, Yaba, Ikeja, Apapa, Lekki, Surulere,
    Ajah, Abuja, Lagos are all real, valid Nigerian locations.
  - Nigerian English usage is not an error: "snap" commonly means photograph/screenshot,
    not literal snapping; other regional phrasing/accent is not a conduct problem.
Only flag something as an agent error if it would still be wrong after mentally
correcting for the above — e.g. the agent actually gives incorrect loan terms, actually
contradicts themselves on facts unrelated to mishearing, is actually rude, or actually
fails to answer a direct question. If the confusing part of a sentence is plausibly just
a transcription glitch (garbled words, mid-sentence non-sequitur with no clear reading),
do not count it as an agent error — note it as a possible transcription issue instead
and do not let it drive the professionalism/clarity scores down.

Score the AGENT's side of the call (not the customer) on:
- professionalism_score (1-5): courteous, patient, no rudeness/dismissiveness/interruption,
  proper greeting and closing. 5 = fully professional throughout.
- clarity_score (1-5): explained things in a way a customer could follow, no rambling,
  confused, or contradictory statements. 5 = clear and confident throughout.
- errors_noted: a list of concrete mistakes the agent made — e.g. gave incorrect
  information, contradicted themselves, failed to answer a direct question, made a
  promise they should not have made. Empty array if none found. Be specific and quote
  or closely paraphrase the moment, don't just say "sounded unsure".
- flag_for_review (boolean): true only if a human QA reviewer should actually listen to
  this call — i.e. professionalism_score <= 2, or clarity_score <= 2, or errors_noted is
  non-empty with something material (not a trivial slip).
- reason: one sentence explaining the flag_for_review decision.

Respond with ONLY a JSON object, no other text:
{"professionalism_score": <1-5>, "clarity_score": <1-5>, "errors_noted": [<string>, ...], "flag_for_review": <bool>, "reason": "<string>"}`

// hdCallQARun transcribes and scores one call on demand.
func hdCallQARun(db *core.DB) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		u := core.UserFromCtx(r.Context())
		if !hdCanSuperviseCalls(u) {
			respondErr(w, 403, "Supervisor access required")
			return
		}
		id := chi.URLParam(r, "id")
		fname, _, expired, ok := hdRecordingCall(r.Context(), db, u, id)
		if !ok {
			respondErr(w, 404, "Call not found")
			return
		}
		if fname == "" || expired {
			respondErr(w, 404, "No recording available for this call")
			return
		}
		if !strings.HasSuffix(strings.ToLower(fname), ".wav") {
			respondErr(w, 501, "QA scoring only supports WAV recordings right now")
			return
		}
		if _, err := os.Stat(callQAWhisperBin()); err != nil {
			respondErr(w, 503, "Call QA is not set up on this server")
			return
		}

		cachePath, err := downloadRecordingToCache(r.Context(), db, id, fname)
		if err != nil {
			respondErrLog(w, 502, "Could not fetch the recording", err)
			return
		}

		// whisper.cpp is CPU-bound and single-threaded per run; serialize so two
		// supervisors clicking "Run QA" at once don't just halve each other's speed.
		callQAMu.Lock()
		defer callQAMu.Unlock()

		ctx, cancel := context.WithTimeout(context.Background(), 8*time.Minute)
		defer cancel()

		transcript, err := callQATranscribe(ctx, cachePath)
		if err != nil {
			respondErrLog(w, 500, "Transcription failed", err)
			return
		}
		if strings.TrimSpace(transcript) == "" {
			respondErr(w, 422, "Transcription produced no text (silent or unreadable recording)")
			return
		}

		score, err := callQAScore(ctx, transcript)
		if err != nil {
			respondErrLog(w, 500, "Scoring failed", err)
			return
		}

		errorsJSON, err := json.Marshal(score.ErrorsNoted)
		if err != nil {
			respondErrLog(w, 500, "Could not encode QA result", err)
			return
		}
		rows, err := db.PGQuery(r.Context(), `
			INSERT INTO app.call_qa_flags
			    (call_id, model, transcript, professionalism_score, clarity_score,
			     errors_noted, flag_for_review, reason, requested_by)
			VALUES ($1,$2,$3,$4,$5,$6::jsonb,$7,$8,$9)
			RETURNING *`,
			id, callQAModelName, transcript, score.Professionalism, score.Clarity,
			string(errorsJSON), score.FlagForReview, score.Reason, u.ID)
		if err != nil {
			respondErrLog(w, 500, "Could not save QA result", err)
			return
		}
		w.Header().Set("Content-Type", "application/json")
		json.NewEncoder(w).Encode(rows[0]) //nolint:errcheck
	}
}

// hdCallQAList lists QA flags, newest first, optionally filtered.
func hdCallQAList(db *core.DB) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		u := core.UserFromCtx(r.Context())
		if !hdCanSuperviseCalls(u) {
			respondErr(w, 403, "Supervisor access required")
			return
		}
		var where []string
		var args []any
		if agent := strings.TrimSpace(r.URL.Query().Get("agent")); agent != "" {
			args = append(args, "%"+agent+"%")
			where = append(where, fmt.Sprintf("c.agent_name ILIKE $%d", len(args)))
		}
		if status := strings.TrimSpace(r.URL.Query().Get("status")); status != "" {
			args = append(args, status)
			where = append(where, fmt.Sprintf("q.review_status = $%d", len(args)))
		}
		if r.URL.Query().Get("flagged_only") == "true" {
			where = append(where, "q.flag_for_review")
		}
		whereSQL := ""
		if len(where) > 0 {
			whereSQL = "WHERE " + strings.Join(where, " AND ")
		}
		rows, err := db.PGQuery(r.Context(), `
			SELECT q.id, q.call_id, q.model, q.professionalism_score, q.clarity_score,
			       q.errors_noted, q.flag_for_review, q.reason, q.review_status,
			       q.review_notes, q.reviewed_by, q.reviewed_at, q.created_at,
			       c.agent_name, c.customer_name, c.started_at, c.duration_sec,
			       c.disposition, c.direction
			  FROM app.call_qa_flags q
			  JOIN app.helpdesk_calls c ON c.id = q.call_id
			  `+whereSQL+`
			 ORDER BY q.created_at DESC
			 LIMIT 200`, args...)
		if err != nil {
			respondErrLog(w, 500, "Could not load QA flags", err)
			return
		}
		jsonRows(w, rows)
	}
}

// hdCallQAReview records a supervisor's disposition of one QA flag.
func hdCallQAReview(db *core.DB) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		u := core.UserFromCtx(r.Context())
		if !hdCanSuperviseCalls(u) {
			respondErr(w, 403, "Supervisor access required")
			return
		}
		id := chi.URLParam(r, "id")
		var body struct {
			Status string `json:"status"`
			Notes  string `json:"notes"`
		}
		if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
			respondErr(w, 400, "Invalid request body")
			return
		}
		if body.Status != "reviewed" && body.Status != "dismissed" && body.Status != "actioned" {
			respondErr(w, 400, "status must be reviewed, dismissed, or actioned")
			return
		}
		rows, err := db.PGQuery(r.Context(), `
			UPDATE app.call_qa_flags
			   SET review_status = $1, review_notes = $2, reviewed_by = $3, reviewed_at = NOW()
			 WHERE id = $4
			 RETURNING *`, body.Status, body.Notes, u.ID, id)
		if err != nil {
			respondErrLog(w, 500, "Could not update QA flag", err)
			return
		}
		if len(rows) == 0 {
			respondErr(w, 404, "QA flag not found")
			return
		}
		w.Header().Set("Content-Type", "application/json")
		json.NewEncoder(w).Encode(rows[0]) //nolint:errcheck
	}
}

// callQATranscribe resamples a cached Zoho recording (8kHz stereo, as Zoho Voice
// delivers it) to the 16kHz mono PCM whisper.cpp requires, then runs
// whisper-cli against it. No ffmpeg on this host, so the resample is hand-
// rolled: downmix channels by averaging, upsample 8kHz->16kHz by linear
// interpolation (phone audio is already band-limited to ~4kHz, so no filter
// is needed).
func callQATranscribe(ctx context.Context, cachedWavPath string) (string, error) {
	raw, err := os.ReadFile(cachedWavPath)
	if err != nil {
		return "", fmt.Errorf("reading cached recording: %w", err)
	}
	fmtChunk, data, err := callQAReadWav(raw)
	if err != nil {
		return "", fmt.Errorf("parsing recording wav: %w", err)
	}
	samples, err := callQAToMono16k(fmtChunk, data)
	if err != nil {
		return "", fmt.Errorf("resampling recording: %w", err)
	}
	wav16k := callQAWriteWav16kMono(samples)

	tmpDir, err := os.MkdirTemp("", "o3c-qa-*")
	if err != nil {
		return "", fmt.Errorf("creating scratch dir: %w", err)
	}
	defer os.RemoveAll(tmpDir)

	inPath := filepath.Join(tmpDir, "in.wav")
	if err := os.WriteFile(inPath, wav16k, 0o644); err != nil {
		return "", fmt.Errorf("writing resampled wav: %w", err)
	}
	outPrefix := filepath.Join(tmpDir, "out")

	cmd := exec.CommandContext(ctx, callQAWhisperBin(),
		"-m", callQAModelPath(),
		"-f", inPath,
		"-otxt", "-of", outPrefix,
		"--carry-initial-prompt", "--prompt", callQAVocabPrompt,
		"-nt",
	)
	var errBuf bytes.Buffer
	cmd.Stderr = &errBuf
	if err := cmd.Run(); err != nil {
		return "", fmt.Errorf("whisper-cli: %w: %s", err, errBuf.String())
	}
	out, err := os.ReadFile(outPrefix + ".txt")
	if err != nil {
		return "", fmt.Errorf("reading transcript: %w", err)
	}
	return strings.TrimSpace(string(out)), nil
}

type callQAScoreResult struct {
	Professionalism int      `json:"professionalism_score"`
	Clarity         int      `json:"clarity_score"`
	ErrorsNoted     []string `json:"errors_noted"`
	FlagForReview   bool     `json:"flag_for_review"`
	Reason          string   `json:"reason"`
}

// callQAScore runs the transcript through the same local Ollama model
// assistant.go uses, so nothing about the call leaves the building.
func callQAScore(ctx context.Context, transcript string) (*callQAScoreResult, error) {
	reqBody, err := json.Marshal(map[string]any{
		"model": "qwen3:4b-instruct",
		"messages": []map[string]string{
			{"role": "system", "content": callQARubric},
			{"role": "user", "content": "TRANSCRIPT:\n" + transcript},
		},
		"format":  "json",
		"stream":  false,
		"options": map[string]any{"temperature": 0.1},
	})
	if err != nil {
		return nil, err
	}
	req, err := http.NewRequestWithContext(ctx, http.MethodPost, "http://127.0.0.1:11434/api/chat", bytes.NewReader(reqBody))
	if err != nil {
		return nil, err
	}
	req.Header.Set("Content-Type", "application/json")
	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		return nil, fmt.Errorf("calling local model: %w", err)
	}
	defer resp.Body.Close()
	var body struct {
		Message struct {
			Content string `json:"content"`
		} `json:"message"`
	}
	if err := json.NewDecoder(resp.Body).Decode(&body); err != nil {
		return nil, fmt.Errorf("decoding model response: %w", err)
	}
	var score callQAScoreResult
	if err := json.Unmarshal([]byte(body.Message.Content), &score); err != nil {
		return nil, fmt.Errorf("model did not return valid JSON: %w", err)
	}
	return &score, nil
}

// --- WAV chunk walking (RIFF), 8kHz/16-bit stereo -> 16kHz/16-bit mono ---

type callQAWavFmt struct {
	AudioFormat   uint16
	NumChannels   uint16
	SampleRate    uint32
	BitsPerSample uint16
}

func callQAReadWav(data []byte) (callQAWavFmt, []byte, error) {
	if len(data) < 12 || string(data[0:4]) != "RIFF" || string(data[8:12]) != "WAVE" {
		return callQAWavFmt{}, nil, fmt.Errorf("not a RIFF/WAVE file")
	}
	var f callQAWavFmt
	var dataChunk []byte
	offset := 12
	for offset+8 <= len(data) {
		id := string(data[offset : offset+4])
		size := int(binary.LittleEndian.Uint32(data[offset+4 : offset+8]))
		body := offset + 8
		if size < 0 || body+size > len(data) {
			break
		}
		switch id {
		case "fmt ":
			if size >= 16 {
				f = callQAWavFmt{
					AudioFormat:   binary.LittleEndian.Uint16(data[body : body+2]),
					NumChannels:   binary.LittleEndian.Uint16(data[body+2 : body+4]),
					SampleRate:    binary.LittleEndian.Uint32(data[body+4 : body+8]),
					BitsPerSample: binary.LittleEndian.Uint16(data[body+14 : body+16]),
				}
			}
		case "data":
			dataChunk = data[body : body+size]
		}
		offset = body + size + (size % 2) // chunks are word-aligned
	}
	if f.AudioFormat == 0 || dataChunk == nil {
		return callQAWavFmt{}, nil, fmt.Errorf("missing fmt or data chunk")
	}
	if f.AudioFormat != 1 || f.BitsPerSample != 16 {
		return callQAWavFmt{}, nil, fmt.Errorf("unsupported format: audioFormat=%d bits=%d", f.AudioFormat, f.BitsPerSample)
	}
	return f, dataChunk, nil
}

func callQAToMono16k(f callQAWavFmt, data []byte) ([]int16, error) {
	ch := int(f.NumChannels)
	if ch < 1 {
		return nil, fmt.Errorf("invalid channel count %d", ch)
	}
	nFrames := len(data) / (2 * ch)
	if nFrames == 0 {
		return nil, fmt.Errorf("recording has no audio frames")
	}
	mono := make([]int16, nFrames)
	for i := 0; i < nFrames; i++ {
		sum := 0
		for c := 0; c < ch; c++ {
			off := (i*ch + c) * 2
			sum += int(int16(binary.LittleEndian.Uint16(data[off : off+2])))
		}
		mono[i] = int16(sum / ch)
	}
	if f.SampleRate == 16000 {
		return mono, nil
	}
	if f.SampleRate != 8000 {
		return nil, fmt.Errorf("unexpected sample rate %d, only 8000/16000 supported", f.SampleRate)
	}
	out := make([]int16, nFrames*2-1)
	for i := 0; i < nFrames; i++ {
		out[i*2] = mono[i]
		if i < nFrames-1 {
			out[i*2+1] = int16((int(mono[i]) + int(mono[i+1])) / 2)
		}
	}
	return out, nil
}

func callQAWriteWav16kMono(samples []int16) []byte {
	dataSize := len(samples) * 2
	buf := make([]byte, 44+dataSize)
	copy(buf[0:4], "RIFF")
	binary.LittleEndian.PutUint32(buf[4:8], uint32(36+dataSize))
	copy(buf[8:12], "WAVE")
	copy(buf[12:16], "fmt ")
	binary.LittleEndian.PutUint32(buf[16:20], 16)
	binary.LittleEndian.PutUint16(buf[20:22], 1) // PCM
	binary.LittleEndian.PutUint16(buf[22:24], 1) // mono
	binary.LittleEndian.PutUint32(buf[24:28], 16000)
	binary.LittleEndian.PutUint32(buf[28:32], 16000*2) // byte rate
	binary.LittleEndian.PutUint16(buf[32:34], 2)       // block align
	binary.LittleEndian.PutUint16(buf[34:36], 16)      // bits per sample
	copy(buf[36:40], "data")
	binary.LittleEndian.PutUint32(buf[40:44], uint32(dataSize))
	for i, s := range samples {
		binary.LittleEndian.PutUint16(buf[44+i*2:46+i*2], uint16(s))
	}
	return buf
}
