-- 242: Management reports -- the scheduled emails, who receives them, and every send.
--
-- The six reports (Daily Operations, Weekly Business Review, Monthly Review, and the
-- three Sales Performance cadences) were generated by scripts that lived outside the
-- workspace, with the recipient list hard-coded in source. Nobody could see whether
-- this morning's email went out, change who gets it, or look at what was sent without
-- someone opening a terminal. These tables make the workspace the control surface:
--
--   * management_reports holds one row per report -- cadence, send time, recipients,
--     on/off. The generator reads recipients from here, so changing the distribution
--     list is an edit in the Reports page, not a code change.
--   * management_report_runs records every build: scheduled, sent on demand, or a
--     preview. preview_html keeps the rendered body (charts inlined) so the page can
--     show exactly what landed in the inbox.
--
-- due_rule is explicit rather than a cron string because the rules are business rules
-- ("Tuesday to Saturday", "the 1st"), and a cron expression hides them from the page.

CREATE TABLE IF NOT EXISTS app.management_reports (
  report_key   TEXT PRIMARY KEY,
  name         TEXT NOT NULL,
  audience     TEXT NOT NULL CHECK (audience IN ('management', 'sales')),
  cadence      TEXT NOT NULL CHECK (cadence IN ('daily', 'weekly', 'monthly')),
  due_rule     TEXT NOT NULL CHECK (due_rule IN ('tue_to_sat', 'monday', 'first_of_month')),
  send_time    TIME NOT NULL DEFAULT '09:00',
  description  TEXT NOT NULL DEFAULT '',
  recipients   JSONB NOT NULL DEFAULT '[]'::jsonb,
  is_active    BOOLEAN NOT NULL DEFAULT TRUE,
  sort_order   INT NOT NULL DEFAULT 0,
  updated_by   BIGINT REFERENCES app.o3c_users(id) ON DELETE SET NULL,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at   TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS app.management_report_runs (
  id                  BIGSERIAL PRIMARY KEY,
  report_key          TEXT NOT NULL REFERENCES app.management_reports(report_key) ON DELETE CASCADE,
  -- schedule: the 09:00 job. manual: "Send now" from the page. preview: built, not sent.
  run_trigger         TEXT NOT NULL DEFAULT 'schedule' CHECK (run_trigger IN ('schedule', 'manual', 'preview')),
  status              TEXT NOT NULL DEFAULT 'running' CHECK (status IN ('running', 'sent', 'built', 'failed', 'skipped')),
  run_date            DATE NOT NULL DEFAULT ((NOW() AT TIME ZONE 'Africa/Lagos')::date),
  requested_by        BIGINT REFERENCES app.o3c_users(id) ON DELETE SET NULL,
  subject             TEXT NOT NULL DEFAULT '',
  recipients          JSONB NOT NULL DEFAULT '[]'::jsonb,
  body_kb             NUMERIC(8, 1),
  chart_count         INT,
  provider_message_id TEXT,
  error               TEXT,
  preview_html        TEXT,
  started_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  finished_at         TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_mgmt_report_runs_key
  ON app.management_report_runs(report_key, started_at DESC);

-- The schedule may send a report at most once a day. A failed attempt does not count,
-- so a retry after a SendGrid outage is still allowed; a send already in flight or
-- delivered blocks a second task run from mailing management twice.
CREATE UNIQUE INDEX IF NOT EXISTS uq_mgmt_report_runs_daily
  ON app.management_report_runs(report_key, run_date)
  WHERE run_trigger = 'schedule' AND status IN ('running', 'sent');

INSERT INTO app.management_reports
       (report_key, name, audience, cadence, due_rule, description, recipients, sort_order)
VALUES
  ('daily',   'Daily Operations',       'management', 'daily',   'tue_to_sat',
   'The previous working day across collections, risk, recovery, calls, cards, deposits and loans.',
   '["babatundeopemiposi@gmail.com","tbabatunde@o3cards.com","temitope_babatunde@outlook.com"]', 10),
  ('weekly',  'Weekly Business Review', 'management', 'weekly',  'monday',
   'Last complete Monday-to-Sunday week, and how far the month has come.',
   '["babatundeopemiposi@gmail.com","tbabatunde@o3cards.com","temitope_babatunde@outlook.com"]', 20),
  ('monthly', 'Monthly Review',         'management', 'monthly', 'first_of_month',
   'The month just closed against the month before it, with every officer against target.',
   '["babatundeopemiposi@gmail.com","tbabatunde@o3cards.com","temitope_babatunde@outlook.com"]', 30),
  ('sales-daily',   'Sales Performance - Daily',   'sales', 'daily',   'tue_to_sat',
   'Deposits and loans against target, individually and by team, for the sales floor.',
   '["babatundeopemiposi@gmail.com","tbabatunde@o3cards.com","temitope_babatunde@outlook.com"]', 40),
  ('sales-weekly',  'Sales Performance - Weekly',  'sales', 'weekly',  'monday',
   'Last week''s bookings and the month-to-date position against target.',
   '["babatundeopemiposi@gmail.com","tbabatunde@o3cards.com","temitope_babatunde@outlook.com"]', 50),
  ('sales-monthly', 'Sales Performance - Monthly', 'sales', 'monthly', 'first_of_month',
   'The closed month: every officer and team against target, and business from outside sales.',
   '["babatundeopemiposi@gmail.com","tbabatunde@o3cards.com","temitope_babatunde@outlook.com"]', 60)
ON CONFLICT (report_key) DO NOTHING;
